/**
 * 6 ECMAScript Data Types and Values https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-data-types-and-values
 */

export {
  isBigInt,
  isBoolean,
  isNull,
  isNumber,
  isObject,
  isPropertyKey,
  isPropertyName,
  isString,
  isSymbol,
  isUndefined,
  type LanguageValue,
  Number_add,
  Number_bitwiseAND,
  Number_bitwiseNOT,
  Number_bitwiseOR,
  Number_bitwiseXOR,
  Number_divide,
  Number_equal,
  Number_exponentiate,
  Number_leftShift,
  Number_lessThan,
  Number_multiply,
  Number_remainder,
  Number_sameValue,
  Number_sameValueZero,
  Number_signedRightShift,
  Number_subtract,
  Number_toString,
  Number_unaryMinus,
  Number_unsignedRightShift,
  NumberBitwiseOp,
  type PropertyName,
  type StrictPropertyKey,
  StringIndexOf,
  StringLastIndexOf,
  type WrappedLanguageValue,
} from "./types/langtypes.ts";
export {
  type CompletionRecord,
  type EnvironmentRecord,
  type EnvrionmentReferenceRecord,
  GetThisValue,
  GetValue,
  IsPrivateReference,
  IsPropertyReference,
  IsSuperReference,
  IsUnresolvableReference,
  type PrivateName,
  type PropertyReferenceRecord,
  type ReferenceRecord,
  type SpecValue,
  type UnresolvableReferenceRecord,
} from "./types/spectypes.ts";
